import { EngagementHook } from '@/types/funnel';

export const ENGAGEMENT_HOOKS: EngagementHook[] = [
  {
    id: 'first_task_complete',
    type: 'achievement',
    title: 'First Task Complete!',
    description: 'You completed your first task. Keep the momentum going!',
    triggerCondition: 'tasks_completed === 1',
    ctaText: 'Create Another Task',
    ctaAction: 'navigate_to_tasks',
  },
  {
    id: 'streak_3_days',
    type: 'streak',
    title: '3 Day Streak!',
    description: 'You\'re building consistency. Can you make it to 7 days?',
    triggerCondition: 'streak_days === 3',
    reward: 'badge_consistent',
    ctaText: 'Keep Going',
    ctaAction: 'dismiss',
  },
  {
    id: 'streak_7_days',
    type: 'streak',
    title: '7 Day Streak!',
    description: 'Amazing! You\'ve completed a full week. Unlock premium to track advanced stats.',
    triggerCondition: 'streak_days === 7',
    reward: 'badge_week_warrior',
    ctaText: 'Upgrade to Premium',
    ctaAction: 'show_paywall',
  },
  {
    id: 'tasks_milestone_10',
    type: 'milestone',
    title: '10 Tasks Completed!',
    description: 'You\'re making great progress. Premium users get unlimited AI breakdowns.',
    triggerCondition: 'tasks_completed === 10',
    ctaText: 'Learn More',
    ctaAction: 'show_paywall',
  },
  {
    id: 'breathing_milestone_5',
    type: 'milestone',
    title: '5 Breathing Sessions!',
    description: 'You\'re mastering mindfulness. Keep up the great work!',
    triggerCondition: 'breathing_sessions === 5',
    ctaText: 'Continue',
    ctaAction: 'navigate_to_wellness',
  },
  {
    id: 'coach_engaged',
    type: 'achievement',
    title: 'AI Coach Activated!',
    description: 'You\'ve discovered your AI coach. Premium unlocks advanced coaching features.',
    triggerCondition: 'coach_interactions === 1',
    ctaText: 'Explore Premium',
    ctaAction: 'show_paywall',
  },
  {
    id: 'weekend_warrior',
    type: 'challenge',
    title: 'Weekend Challenge',
    description: 'Complete 3 tasks this weekend to earn a special badge!',
    triggerCondition: 'is_weekend && tasks_completed_today < 3',
    reward: 'badge_weekend_warrior',
    ctaText: 'Accept Challenge',
    ctaAction: 'navigate_to_tasks',
  },
  {
    id: 'comeback_bonus',
    type: 'social',
    title: 'Welcome Back!',
    description: 'We missed you! Complete a task today to restart your streak.',
    triggerCondition: 'days_since_last_active >= 3',
    ctaText: 'Get Started',
    ctaAction: 'navigate_to_tasks',
  },
];
