import { MentalHealthResource, BreathingPattern } from '@/types/mentalHealth';
import colors from './colors';

export const mentalHealthResources: MentalHealthResource[] = [
  {
    id: '1',
    title: '988 Suicide & Crisis Lifeline',
    description: '24/7 free and confidential support for people in distress',
    category: 'crisis',
    phone: '988',
    available24x7: true,
    icon: 'phone',
  },
  {
    id: '2',
    title: 'Crisis Text Line',
    description: 'Text HOME to 741741 for free 24/7 crisis support',
    category: 'crisis',
    phone: '741741',
    available24x7: true,
    icon: 'message-circle',
  },
  {
    id: '3',
    title: 'NAMI Helpline',
    description: 'National Alliance on Mental Illness support and resources',
    category: 'support',
    phone: '1-800-950-6264',
    available24x7: false,
    icon: 'heart',
  },
  {
    id: '4',
    title: 'SAMHSA National Helpline',
    description: 'Treatment referral and information service',
    category: 'support',
    phone: '1-800-662-4357',
    available24x7: true,
    icon: 'info',
  },
  {
    id: '5',
    title: 'Autism Society',
    description: 'Support and resources for autism spectrum',
    category: 'support',
    phone: '1-800-328-8476',
    icon: 'users',
  },
  {
    id: '6',
    title: 'CHADD (ADHD Support)',
    description: 'Children and Adults with ADHD resources',
    category: 'education',
    url: 'https://chadd.org',
    icon: 'book-open',
  },
  {
    id: '7',
    title: 'Anxiety & Depression Association',
    description: 'Resources and support for anxiety disorders',
    category: 'education',
    url: 'https://adaa.org',
    icon: 'shield',
  },
  {
    id: '8',
    title: 'BetterHelp',
    description: 'Online therapy and counseling services',
    category: 'therapy',
    url: 'https://betterhelp.com',
    icon: 'video',
  },
  {
    id: '9',
    title: 'Alzheimer\'s Association',
    description: '24/7 helpline for dementia support and resources',
    category: 'support',
    phone: '1-800-272-3900',
    available24x7: true,
    icon: 'brain',
  },
  {
    id: '10',
    title: 'Alzheimer\'s Foundation of America',
    description: 'Support, education, and resources for dementia care',
    category: 'support',
    phone: '1-866-232-8484',
    available24x7: false,
    icon: 'heart-handshake',
  },
  {
    id: '11',
    title: 'Dementia Society of America',
    description: 'Resources and support for dementia patients and caregivers',
    category: 'education',
    url: 'https://www.dementiasociety.org',
    icon: 'book-open',
  },
  {
    id: '12',
    title: 'National Institute on Aging',
    description: 'Research and information on Alzheimer\'s and dementia',
    category: 'education',
    url: 'https://www.nia.nih.gov/health/alzheimers',
    icon: 'microscope',
  },
  {
    id: '13',
    title: 'Caregiver Action Network',
    description: 'Support and resources for family caregivers',
    category: 'support',
    phone: '1-855-227-3640',
    icon: 'users',
  },
];

export const caregiverResources: MentalHealthResource[] = [
  {
    id: 'cg1',
    title: 'Caregiver Action Network',
    description: 'Education, peer support, and resources for family caregivers',
    category: 'support',
    phone: '1-855-227-3640',
    url: 'https://caregiveraction.org',
    icon: 'users',
  },
  {
    id: 'cg2',
    title: 'Family Caregiver Alliance',
    description: 'National center on caregiving with resources and support',
    category: 'support',
    phone: '1-800-445-8106',
    url: 'https://www.caregiver.org',
    icon: 'heart',
  },
  {
    id: 'cg3',
    title: 'ARCH National Respite Network',
    description: 'Find respite care services in your area',
    category: 'support',
    phone: '1-703-256-2084',
    url: 'https://archrespite.org',
    icon: 'clock',
  },
  {
    id: 'cg4',
    title: 'Alzheimer\'s Association Caregiver Support',
    description: '24/7 helpline for dementia caregivers',
    category: 'crisis',
    phone: '1-800-272-3900',
    available24x7: true,
    url: 'https://www.alz.org/help-support/caregiving',
    icon: 'phone',
  },
  {
    id: 'cg5',
    title: 'National Alliance for Caregiving',
    description: 'Research, advocacy, and resources for caregivers',
    category: 'education',
    url: 'https://www.caregiving.org',
    icon: 'book-open',
  },
  {
    id: 'cg6',
    title: 'Eldercare Locator',
    description: 'Connect to services for older adults and caregivers',
    category: 'support',
    phone: '1-800-677-1116',
    url: 'https://eldercare.acl.gov',
    icon: 'map-pin',
  },
  {
    id: 'cg7',
    title: 'AARP Caregiving Resource Center',
    description: 'Tools, tips, and support for family caregivers',
    category: 'education',
    url: 'https://www.aarp.org/caregiving',
    icon: 'info',
  },
  {
    id: 'cg8',
    title: 'Caregiver Stress & Burnout Prevention',
    description: 'Mental health resources specifically for caregivers',
    category: 'therapy',
    url: 'https://www.helpguide.org/articles/stress/caregiver-stress-and-burnout.htm',
    icon: 'shield',
  },
  {
    id: 'cg9',
    title: 'National Respite Locator',
    description: 'Find respite care providers near you',
    category: 'support',
    url: 'https://archrespite.org/respitelocator',
    icon: 'search',
  },
  {
    id: 'cg10',
    title: 'Caregiver Support Groups',
    description: 'Connect with other caregivers in your community',
    category: 'support',
    url: 'https://www.caregiver.org/connecting-caregivers/support-groups',
    icon: 'users',
  },
  {
    id: 'cg11',
    title: 'Medicare Caregiver Resources',
    description: 'Understanding Medicare benefits for caregiving',
    category: 'education',
    phone: '1-800-633-4227',
    url: 'https://www.medicare.gov/caregivers',
    icon: 'file-text',
  },
  {
    id: 'cg12',
    title: 'Veterans Affairs Caregiver Support',
    description: 'Resources for caregivers of veterans',
    category: 'support',
    phone: '1-855-260-3274',
    url: 'https://www.caregiver.va.gov',
    icon: 'shield',
  },
];

export const cognitiveResources: MentalHealthResource[] = [
  {
    id: 'cog1',
    title: '988 Suicide & Crisis Lifeline',
    description: '24/7 free and confidential support for people in distress',
    category: 'crisis',
    phone: '988',
    available24x7: true,
    icon: 'phone',
  },
  {
    id: 'cog2',
    title: 'Crisis Text Line',
    description: 'Text HOME to 741741 for free 24/7 crisis support',
    category: 'crisis',
    phone: '741741',
    available24x7: true,
    icon: 'message-circle',
  },
  {
    id: 'cog3',
    title: 'NAMI Helpline',
    description: 'National Alliance on Mental Illness support and resources',
    category: 'support',
    phone: '1-800-950-6264',
    available24x7: false,
    icon: 'heart',
  },
  {
    id: 'cog4',
    title: 'Autism Society',
    description: 'Support and resources for autism spectrum',
    category: 'support',
    phone: '1-800-328-8476',
    url: 'https://www.autism-society.org',
    icon: 'users',
  },
  {
    id: 'cog5',
    title: 'CHADD (ADHD Support)',
    description: 'Children and Adults with ADHD resources',
    category: 'education',
    phone: '1-800-233-4050',
    url: 'https://chadd.org',
    icon: 'book-open',
  },
  {
    id: 'cog6',
    title: 'Anxiety & Depression Association',
    description: 'Resources and support for anxiety disorders',
    category: 'education',
    url: 'https://adaa.org',
    icon: 'shield',
  },
  {
    id: 'cog7',
    title: 'Learning Disabilities Association',
    description: 'Support for learning differences and cognitive challenges',
    category: 'support',
    phone: '1-412-341-1515',
    url: 'https://ldaamerica.org',
    icon: 'info',
  },
  {
    id: 'cog8',
    title: 'Understood.org',
    description: 'Resources for learning and thinking differences',
    category: 'education',
    url: 'https://www.understood.org',
    icon: 'book-open',
  },
  {
    id: 'cog9',
    title: 'BetterHelp',
    description: 'Online therapy and counseling services',
    category: 'therapy',
    url: 'https://betterhelp.com',
    icon: 'video',
  },
  {
    id: 'cog10',
    title: 'SAMHSA National Helpline',
    description: 'Treatment referral and information service',
    category: 'support',
    phone: '1-800-662-4357',
    available24x7: true,
    icon: 'info',
  },
  {
    id: 'cog11',
    title: 'Mental Health America',
    description: 'Screening tools and mental health resources',
    category: 'education',
    url: 'https://www.mhanational.org',
    icon: 'heart',
  },
  {
    id: 'cog12',
    title: 'Neurodiversity Hub',
    description: 'Celebrating and supporting neurodivergent individuals',
    category: 'support',
    url: 'https://www.neurodiversityhub.org',
    icon: 'users',
  },
];

export const memoryResources: MentalHealthResource[] = [
  {
    id: 'mem1',
    title: 'Alzheimer\'s Association 24/7 Helpline',
    description: 'Free support, information and referrals',
    category: 'crisis',
    phone: '1-800-272-3900',
    available24x7: true,
    icon: 'phone',
  },
  {
    id: 'mem2',
    title: 'Alzheimer\'s Foundation of America',
    description: 'Support, education, and resources for dementia care',
    category: 'support',
    phone: '1-866-232-8484',
    url: 'https://alzfdn.org',
    icon: 'heart',
  },
  {
    id: 'mem3',
    title: 'Dementia Society of America',
    description: 'Resources and support for dementia patients',
    category: 'support',
    url: 'https://www.dementiasociety.org',
    icon: 'users',
  },
  {
    id: 'mem4',
    title: 'National Institute on Aging',
    description: 'Research and information on Alzheimer\'s and dementia',
    category: 'education',
    url: 'https://www.nia.nih.gov/health/alzheimers',
    icon: 'book-open',
  },
  {
    id: 'mem5',
    title: 'Alzheimer\'s Disease Education',
    description: 'Information center for patients and families',
    category: 'education',
    phone: '1-800-438-4380',
    url: 'https://www.nia.nih.gov/health/alzheimers',
    icon: 'info',
  },
  {
    id: 'mem6',
    title: 'UsAgainstAlzheimer\'s',
    description: 'Advocacy and support for Alzheimer\'s patients',
    category: 'support',
    url: 'https://www.usagainstalzheimers.org',
    icon: 'shield',
  },
  {
    id: 'mem7',
    title: 'Memory Cafes',
    description: 'Social gatherings for people with memory loss',
    category: 'support',
    url: 'https://www.memorycafedirectory.com',
    icon: 'users',
  },
  {
    id: 'mem8',
    title: 'BrightFocus Foundation',
    description: 'Alzheimer\'s research and education',
    category: 'education',
    phone: '1-800-437-2423',
    url: 'https://www.brightfocus.org/alzheimers',
    icon: 'book-open',
  },
  {
    id: 'mem9',
    title: 'Lewy Body Dementia Association',
    description: 'Support for Lewy body dementia patients',
    category: 'support',
    phone: '1-800-539-9767',
    url: 'https://www.lbda.org',
    icon: 'heart',
  },
  {
    id: 'mem10',
    title: 'Association for Frontotemporal Degeneration',
    description: 'Resources for FTD patients and families',
    category: 'support',
    phone: '1-866-507-7222',
    url: 'https://www.theaftd.org',
    icon: 'info',
  },
  {
    id: 'mem11',
    title: 'Eldercare Locator',
    description: 'Connect to local services for older adults',
    category: 'support',
    phone: '1-800-677-1116',
    url: 'https://eldercare.acl.gov',
    icon: 'map-pin',
  },
  {
    id: 'mem12',
    title: 'Medicare Information',
    description: 'Understanding Medicare coverage for dementia care',
    category: 'education',
    phone: '1-800-633-4227',
    url: 'https://www.medicare.gov',
    icon: 'file-text',
  },
];

export const breathingPatterns: BreathingPattern[] = [
  {
    id: '1',
    name: 'Box Breathing',
    description: 'Simple 4-count breathing for calm',
    inhale: 4,
    hold: 4,
    exhale: 4,
    holdAfterExhale: 4,
    cycles: 3,
    color: colors.primary,
  },
  {
    id: '2',
    name: '4-7-8 Breathing',
    description: 'Promotes relaxation and sleep',
    inhale: 4,
    hold: 7,
    exhale: 8,
    cycles: 4,
    color: colors.secondary,
  },
  {
    id: '3',
    name: 'Calm Breathing',
    description: 'Gentle breathing, no holding',
    inhale: 4,
    hold: 0,
    exhale: 6,
    cycles: 3,
    color: colors.decorative.lavender,
  },
  {
    id: '4',
    name: 'Energizing Breath',
    description: 'Quick technique to boost focus',
    inhale: 3,
    hold: 3,
    exhale: 3,
    cycles: 6,
    color: colors.accent,
  },
  {
    id: '5',
    name: 'Deep Relaxation',
    description: 'Extended breathing for deep calm',
    inhale: 5,
    hold: 5,
    exhale: 7,
    cycles: 3,
    color: colors.decorative.mint,
  },
];
