import { TooltipConfig } from '@/types/funnel';

export const TOOLTIPS: TooltipConfig[] = [
  {
    id: 'first_task',
    title: 'Create Your First Task',
    description: 'Tap the + button to add a task. Our AI will help break it down into manageable steps.',
    targetFeature: 'task_create',
    priority: 1,
    showAfterStep: 'onboarding_complete',
    showOnlyOnce: true,
    delayMs: 2000,
  },
  {
    id: 'breathing_exercise',
    title: 'Take a Breath',
    description: 'Feeling overwhelmed? Try our guided breathing exercises to reduce stress and improve focus.',
    targetFeature: 'breathing',
    priority: 2,
    showAfterStep: 'first_task_create',
    showOnlyOnce: true,
    delayMs: 3000,
  },
  {
    id: 'ai_coach',
    title: 'Meet Nexa',
    description: 'Your AI coach provides personalized task suggestions, motivation, and strategies tailored to your needs.',
    targetFeature: 'coach',
    priority: 3,
    showAfterStep: 'first_task_complete',
    showOnlyOnce: true,
    delayMs: 2000,
  },
  {
    id: 'progress_tracking',
    title: 'Track Your Progress',
    description: 'See your achievements, streaks, and growth over time. Celebrate every win!',
    targetFeature: 'progress',
    priority: 4,
    showAfterStep: 'breathing_complete_session',
    showOnlyOnce: true,
    delayMs: 2000,
  },
  {
    id: 'caregiver_support',
    title: 'Invite a Caregiver',
    description: 'Share your progress with trusted caregivers, therapists, or family members for extra support.',
    targetFeature: 'caregiver',
    priority: 5,
    showAfterStep: 'coach_first_interaction',
    showOnlyOnce: true,
    delayMs: 3000,
  },
  {
    id: 'wellness_hub',
    title: 'Explore Wellness Resources',
    description: 'Access mental health resources, crisis support, and self-care tools whenever you need them.',
    targetFeature: 'wellness',
    priority: 6,
    showOnlyOnce: true,
    delayMs: 2000,
  },
];
